import "./globals.css";
import { Inter } from "next/font/google";
import { Lato } from "@next/font/google";

// const inter = Inter({ subsets: ["latin"] });

const lato = Lato({ subsets: ["latin"], weight: "400" });

export const metadata = {
   title: "Marquis Sampson Resume Website",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={lato.className}>{children}</body>
      </html>
   );
}
