import "src/app/globals.css";
import { Inter } from "next/font/google";
import * as React from "react";

import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Marquis Sampson Resume Website",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en" suppressHydrationWarning={true}>
         <body className={inter.className}>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
